DROP TABLE IF EXIST ODONTOLOGOS;
CREATE TABLE ODONTOLOGOS (NOMBRE VARCHAR(100) NOT NULL, APELLIDO VARCHAR(100) NOT NULL, MATRICULA VARCHAR(20) PRIMARY_KEY);
INSERT INTO ODONTOLOGOS(NOMBRE. APELLIDO, MATRICULA) VALUES("CARLOS","SADA","1234");
INSERT INTO ODONTOLOGOS(NOMBRE. APELLIDO, MATRICULA) VALUES("MATIAS","DADA","1432");
INSERT INTO ODONTOLOGOS(NOMBRE. APELLIDO, MATRICULA) VALUES("ANA","XCVXV","4324");
