DROP TABLE IF EXISTS ODONTOLOGOS;
CREATE TABLE ODONTOLOGOS (MATRICULA VARCHAR(100) PRIMARY KEY, NOMBRE VARCHAR(100) NOT NULL, APELLIDO VARCHAR(100) NOT NULL);

-- para test --
INSERT INTO ODONTOLOGOS(MATRICULA, NOMBRE, APELLIDO) VALUES ('1234', 'Jorge', 'Perez'), ('1342', 'Luis', 'Diaz');
